// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: tccpb/tcc.proto

package tccpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TccOp int32

const (
	TccOp_Invalid TccOp = 0
	TccOp_Try     TccOp = 1
	TccOp_Confirm TccOp = 2
	TccOp_Cancel  TccOp = 3
)

// Enum value maps for TccOp.
var (
	TccOp_name = map[int32]string{
		0: "Invalid",
		1: "Try",
		2: "Confirm",
		3: "Cancel",
	}
	TccOp_value = map[string]int32{
		"Invalid": 0,
		"Try":     1,
		"Confirm": 2,
		"Cancel":  3,
	}
)

func (x TccOp) Enum() *TccOp {
	p := new(TccOp)
	*p = x
	return p
}

func (x TccOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TccOp) Descriptor() protoreflect.EnumDescriptor {
	return file_tccpb_tcc_proto_enumTypes[0].Descriptor()
}

func (TccOp) Type() protoreflect.EnumType {
	return &file_tccpb_tcc_proto_enumTypes[0]
}

func (x TccOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TccOp.Descriptor instead.
func (TccOp) EnumDescriptor() ([]byte, []int) {
	return file_tccpb_tcc_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tccpb_tcc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_tccpb_tcc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_tccpb_tcc_proto_rawDescGZIP(), []int{0}
}

type TccRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op       TccOp             `protobuf:"varint,1,opt,name=op,proto3,enum=tccpb.TccOp" json:"op,omitempty"`
	Payloads string            `protobuf:"bytes,2,opt,name=payloads,proto3" json:"payloads,omitempty"`
	Gid      string            `protobuf:"bytes,3,opt,name=gid,proto3" json:"gid,omitempty"`
	BranchId string            `protobuf:"bytes,4,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Header   map[string]string `protobuf:"bytes,5,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TccRequest) Reset() {
	*x = TccRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tccpb_tcc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TccRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TccRequest) ProtoMessage() {}

func (x *TccRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tccpb_tcc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TccRequest.ProtoReflect.Descriptor instead.
func (*TccRequest) Descriptor() ([]byte, []int) {
	return file_tccpb_tcc_proto_rawDescGZIP(), []int{1}
}

func (x *TccRequest) GetOp() TccOp {
	if x != nil {
		return x.Op
	}
	return TccOp_Invalid
}

func (x *TccRequest) GetPayloads() string {
	if x != nil {
		return x.Payloads
	}
	return ""
}

func (x *TccRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *TccRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *TccRequest) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_tccpb_tcc_proto protoreflect.FileDescriptor

var file_tccpb_tcc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x63, 0x63, 0x70, 0x62, 0x2f, 0x74, 0x63, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x74, 0x63, 0x63, 0x70, 0x62, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0xe7, 0x01, 0x0a, 0x0a, 0x54, 0x63, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x74,
	0x63, 0x63, 0x70, 0x62, 0x2e, 0x54, 0x63, 0x63, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x63, 0x63, 0x70,
	0x62, 0x2e, 0x54, 0x63, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x1a, 0x39, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x36, 0x0a, 0x05, 0x54,
	0x63, 0x63, 0x4f, 0x70, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x72, 0x79, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x10, 0x03, 0x32, 0x34, 0x0a, 0x03, 0x54, 0x63, 0x63, 0x12, 0x2d, 0x0a, 0x0a, 0x45, 0x78,
	0x65, 0x63, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x11, 0x2e, 0x74, 0x63, 0x63, 0x70, 0x62,
	0x2e, 0x54, 0x63, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x74, 0x63,
	0x63, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f,
	0x74, 0x63, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tccpb_tcc_proto_rawDescOnce sync.Once
	file_tccpb_tcc_proto_rawDescData = file_tccpb_tcc_proto_rawDesc
)

func file_tccpb_tcc_proto_rawDescGZIP() []byte {
	file_tccpb_tcc_proto_rawDescOnce.Do(func() {
		file_tccpb_tcc_proto_rawDescData = protoimpl.X.CompressGZIP(file_tccpb_tcc_proto_rawDescData)
	})
	return file_tccpb_tcc_proto_rawDescData
}

var file_tccpb_tcc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tccpb_tcc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tccpb_tcc_proto_goTypes = []interface{}{
	(TccOp)(0),         // 0: tccpb.TccOp
	(*Empty)(nil),      // 1: tccpb.Empty
	(*TccRequest)(nil), // 2: tccpb.TccRequest
	nil,                // 3: tccpb.TccRequest.HeaderEntry
}
var file_tccpb_tcc_proto_depIdxs = []int32{
	0, // 0: tccpb.TccRequest.op:type_name -> tccpb.TccOp
	3, // 1: tccpb.TccRequest.header:type_name -> tccpb.TccRequest.HeaderEntry
	2, // 2: tccpb.Tcc.ExecBranch:input_type -> tccpb.TccRequest
	1, // 3: tccpb.Tcc.ExecBranch:output_type -> tccpb.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tccpb_tcc_proto_init() }
func file_tccpb_tcc_proto_init() {
	if File_tccpb_tcc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tccpb_tcc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tccpb_tcc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TccRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tccpb_tcc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tccpb_tcc_proto_goTypes,
		DependencyIndexes: file_tccpb_tcc_proto_depIdxs,
		EnumInfos:         file_tccpb_tcc_proto_enumTypes,
		MessageInfos:      file_tccpb_tcc_proto_msgTypes,
	}.Build()
	File_tccpb_tcc_proto = out.File
	file_tccpb_tcc_proto_rawDesc = nil
	file_tccpb_tcc_proto_goTypes = nil
	file_tccpb_tcc_proto_depIdxs = nil
}
