// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: tcpb/tc.proto

package tcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Invalid Status = 0
	Status_Prepare Status = 1
	Status_Submit  Status = 2
	Status_Abort   Status = 3
	Status_Success Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Invalid",
		1: "Prepare",
		2: "Submit",
		3: "Abort",
		4: "Success",
	}
	Status_value = map[string]int32{
		"Invalid": 0,
		"Prepare": 1,
		"Submit":  2,
		"Abort":   3,
		"Success": 4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tcpb_tc_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_tcpb_tc_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_tcpb_tc_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcpb_tc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_tcpb_tc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_tcpb_tc_proto_rawDescGZIP(), []int{0}
}

type TranRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid       string `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	TransType string `protobuf:"bytes,2,opt,name=trans_type,json=transType,proto3" json:"trans_type,omitempty"` // tcc, saga, ...
	Status    Status `protobuf:"varint,3,opt,name=status,proto3,enum=tcpb.Status" json:"status,omitempty"`
	Payloads  string `protobuf:"bytes,4,opt,name=payloads,proto3" json:"payloads,omitempty"`
	Reason    string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"` // 失败原因
}

func (x *TranRequest) Reset() {
	*x = TranRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcpb_tc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranRequest) ProtoMessage() {}

func (x *TranRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcpb_tc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranRequest.ProtoReflect.Descriptor instead.
func (*TranRequest) Descriptor() ([]byte, []int) {
	return file_tcpb_tc_proto_rawDescGZIP(), []int{1}
}

func (x *TranRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *TranRequest) GetTransType() string {
	if x != nil {
		return x.TransType
	}
	return ""
}

func (x *TranRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Invalid
}

func (x *TranRequest) GetPayloads() string {
	if x != nil {
		return x.Payloads
	}
	return ""
}

func (x *TranRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BranchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid      string            `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	BranchId string            `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Resource string            `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`                                                                                     // 业务需要的资源
	Header   map[string]string `protobuf:"bytes,4,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 业务自定义数据，比如tc推动submit和abort的调用信息
}

func (x *BranchRequest) Reset() {
	*x = BranchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcpb_tc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchRequest) ProtoMessage() {}

func (x *BranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcpb_tc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchRequest.ProtoReflect.Descriptor instead.
func (*BranchRequest) Descriptor() ([]byte, []int) {
	return file_tcpb_tc_proto_rawDescGZIP(), []int{2}
}

func (x *BranchRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *BranchRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *BranchRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *BranchRequest) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_tcpb_tc_proto protoreflect.FileDescriptor

var file_tcpb_tc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x63, 0x70, 0x62, 0x2f, 0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x74, 0x63, 0x70, 0x62, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x98,
	0x01, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x69, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x24, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x74, 0x63, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xce, 0x01, 0x0a, 0x0d, 0x42, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x67,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x63, 0x70, 0x62, 0x2e, 0x42, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x1a,
	0x39, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x46, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x62,
	0x6f, 0x72, 0x74, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x04, 0x32, 0xb7, 0x01, 0x0a, 0x03, 0x64, 0x74, 0x66, 0x12, 0x29, 0x0a, 0x07, 0x50, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x11, 0x2e, 0x74, 0x63, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x74, 0x63, 0x70, 0x62, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x28, 0x0a, 0x06, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12,
	0x11, 0x2e, 0x74, 0x63, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x74, 0x63, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x27, 0x0a, 0x05, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x12, 0x11, 0x2e, 0x74, 0x63, 0x70, 0x62, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x74, 0x63,
	0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x32, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x13, 0x2e, 0x74, 0x63, 0x70,
	0x62, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0b, 0x2e, 0x74, 0x63, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2e, 0x2f, 0x74, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tcpb_tc_proto_rawDescOnce sync.Once
	file_tcpb_tc_proto_rawDescData = file_tcpb_tc_proto_rawDesc
)

func file_tcpb_tc_proto_rawDescGZIP() []byte {
	file_tcpb_tc_proto_rawDescOnce.Do(func() {
		file_tcpb_tc_proto_rawDescData = protoimpl.X.CompressGZIP(file_tcpb_tc_proto_rawDescData)
	})
	return file_tcpb_tc_proto_rawDescData
}

var file_tcpb_tc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tcpb_tc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tcpb_tc_proto_goTypes = []interface{}{
	(Status)(0),           // 0: tcpb.Status
	(*Empty)(nil),         // 1: tcpb.Empty
	(*TranRequest)(nil),   // 2: tcpb.TranRequest
	(*BranchRequest)(nil), // 3: tcpb.BranchRequest
	nil,                   // 4: tcpb.BranchRequest.HeaderEntry
}
var file_tcpb_tc_proto_depIdxs = []int32{
	0, // 0: tcpb.TranRequest.status:type_name -> tcpb.Status
	4, // 1: tcpb.BranchRequest.header:type_name -> tcpb.BranchRequest.HeaderEntry
	2, // 2: tcpb.dtf.Prepare:input_type -> tcpb.TranRequest
	2, // 3: tcpb.dtf.Submit:input_type -> tcpb.TranRequest
	2, // 4: tcpb.dtf.Abort:input_type -> tcpb.TranRequest
	3, // 5: tcpb.dtf.RegisterBranch:input_type -> tcpb.BranchRequest
	1, // 6: tcpb.dtf.Prepare:output_type -> tcpb.Empty
	1, // 7: tcpb.dtf.Submit:output_type -> tcpb.Empty
	1, // 8: tcpb.dtf.Abort:output_type -> tcpb.Empty
	1, // 9: tcpb.dtf.RegisterBranch:output_type -> tcpb.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tcpb_tc_proto_init() }
func file_tcpb_tc_proto_init() {
	if File_tcpb_tc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tcpb_tc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tcpb_tc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tcpb_tc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BranchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tcpb_tc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tcpb_tc_proto_goTypes,
		DependencyIndexes: file_tcpb_tc_proto_depIdxs,
		EnumInfos:         file_tcpb_tc_proto_enumTypes,
		MessageInfos:      file_tcpb_tc_proto_msgTypes,
	}.Build()
	File_tcpb_tc_proto = out.File
	file_tcpb_tc_proto_rawDesc = nil
	file_tcpb_tc_proto_goTypes = nil
	file_tcpb_tc_proto_depIdxs = nil
}
